# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: CC-PDM-1.0

[tool.black]
line-length = 180

[tool.pytest.ini_options]
addopts = ["-vvv", "-n", "2", "--log-level", "WARNING", "--color", "yes"]
filterwarnings = ['ignore:AnsibleCollectionFinder has already been configured']
testpaths = ["tests"]
